name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false

      - name: Configure
        uses: docker://devkitpro/devkitarm
        with:
          args: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        uses: docker://devkitpro/devkitarm
        with:
          args: cmake --build build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 3DSX
          path: build/SaveSync.3dsx
          if-no-files-found: error