name: Build
on:
  push:
    branches: [ master ]

env:
  dev_tag: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false

      - name: Download makerom
        continue-on-error: true
        run: |
          curl -L -o makerom.zip https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.3/makerom-v0.18.3-ubuntu_x86_64.zip
          unzip makerom.zip
          chmod +x ./makerom

      - name: Download bannertool
        continue-on-error: true
        run: |
          curl -L -o bannertool.zip https://github.com/Epicpkmn11/bannertool/releases/download/v1.2.2/bannertool.zip
          unzip -p bannertool.zip "linux-x86_64/bannertool" > bannertool
          chmod +x ./bannertool
            
      - name: Configure
        uses: docker://devkitpro/devkitarm
        with:
          args: bash -c "git config --global --add safe.directory /github/workspace && cmake -S . -B build -DCMAKE_BUILD_TYPE=Release"

      - name: Build
        uses: docker://devkitpro/devkitarm
        with:
          args: bash -c "git config --global --add safe.directory /github/workspace && cmake --build build"

      - name: Delete Old Latest Release
        uses: cb80/delrel@latest
        with:
          tag: ${{ env.dev_tag }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Create New Latest Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.dev_tag }}
          tag_exists_error: false
          github_token: ${{ secrets.REPO_TOKEN }}
          message: "Latest Release"

      - name: Create Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: Automatic release from master
          files: |
            build/SaveSync.3dsx
            build/SaveSync.cia
          tag_name: ${{ env.dev_tag }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: |
            build/SaveSync.3dsx
            build/SaveSync.cia
          if-no-files-found: warn