name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false

      - name: Download makerom
        continue-on-error: true
        run: |
          curl -L -o makerom.zip https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.3/makerom-v0.18.3-ubuntu_x86_64.zip
          unzip makerom.zip
          chmod +x ./makerom

      - name: Download bannertool
        continue-on-error: true
        run: |
          curl -L -o bannertool.zip https://github.com/Epicpkmn11/bannertool/releases/download/v1.2.2/bannertool.zip
          unzip -p bannertool.zip "linux-x86_64/bannertool" > bannertool
          chmod +x ./bannertool
            
      - name: Configure
        uses: docker://devkitpro/devkitarm
        with:
          args: bash -c "git config --global --add safe.directory /github/workspace && cmake -S . -B build -DCMAKE_BUILD_TYPE=Release"

      - name: Build
        uses: docker://devkitpro/devkitarm
        with:
          args: bash -c "git config --global --add safe.directory /github/workspace && cmake --build build"

      - uses: actions/github-script@v8
        continue-on-error: true
        with:
          github-token: ${{secrets.REPO_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.rest.repos.getReleaseByTag({ owner, repo, tag: '${{ github.ref_name }}' })
            await github.rest.repos.deleteRelease({ owner, repo, release_id: id })

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: Automatic release from master
          files: |
            build/SaveSync.3dsx
            build/SaveSync.cia
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: |
            build/SaveSync.3dsx
            build/SaveSync.cia
          if-no-files-found: warn