name: Test Build
on: [ pull_request ]

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false

      - name: Configure
        run: catnip build debug

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: 3DSX
          path: build/SaveSync.debug/SaveSync.3dsx

  upload:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: test_build

    steps:
      - name: Post comment
        uses: live-codes/pr-comment-from-artifact@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          artifact: 3DSX