name: Test Build
on: [ pull_request ]

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false

      - name: Configure
        run: catnip build debug

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: SaveSync.3dsx
          path: build/SaveSync.debug/SaveSync.3dsx
          if-no-files-found: error